### ISSUE TITLE
Errno 48 Address already in use

### ISSUE THREAD

**Issue by Astroman** [n8henrie/fauxmo#2]
I’m trying to use your version of fauxmo and almost have it working. When I run it though it complains that it can’t initialize the UPnP sockets because the address is already in use. I've tried rebooting with no change. I’m not a developer but I can usually slog through something like this. Not this time though. Any clues would be much appreciated since this is so much better than my previous attempts to integrate Echo with my Indigo home automation software via a custom skill. Thanks!

Here is the verbose terminal output:

fauxmo -vv
2016-02-19 23:15:49 fauxmo       ERROR    Failed to initialize UPnP sockets:
Traceback (most recent call last):
 File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fauxmo/upnp.py", line 189, in init_socket
   self.ssock.bind(('', self.port))
OSError: [Errno 48] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fauxmo/upnp.py", line 192, in init_socket
   self.port))
IndexError: tuple index out of range
2016-02-19 23:15:49 fauxmo       INFO     Using config: ./config.json
2016-02-19 23:15:49 fauxmo       DEBUG    Attempting to get IP address automatically
2016-02-19 23:15:49 fauxmo       DEBUG    Using IP address: xxx
2016-02-19 23:15:49 fauxmo       DEBUG    Attempting to bind: xxx:12345
2016-02-19 23:15:49 fauxmo       DEBUG    UPnP broadcast listener: new device registered
2016-02-19 23:15:49 fauxmo       DEBUG    Device hall light ready on xxx:12345
2016-02-19 23:15:49 fauxmo       DEBUG    {'name': 'hall light', 'listener': <fauxmo.upnp.UpnpBroadcastResponder object at 0x1021c6b38>, 'root_url': 'http://{}:{}/setup.xml', 'port': 12345, 'server_version': 'Unspecified, UPnP/1.0, Unspecified', 'client_sockets': {}, 'socket': <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('xxx', 12345)>, 'action_handler': <fauxmo.handlers.rest.RestApiHandler object at 0x1021c6f60>, 'poller': <fauxmo.upnp.Poller object at 0x1021c6a58>, 'ip_address': 'xxx', 'uuid': UUID('xxx'), 'serial': 'xxx', 'other_headers': ['X-User-Agent: Fauxmo']}
2016-02-19 23:15:49 fauxmo       DEBUG    Entering main loop (polling)

**Comment by Astroman** [comment]
I forgot to include some info about my system:
Fauxmo 0.1.11
Python 3.5.1
MacOS 10.10.5 Yosemite

**Comment by Astroman** [comment]
Found it! My Plex server was using port 1900.

**Comment by n8henrie** [comment]
Great, glad you got it figured out. I wonder if there's a workaround for this -- 1900 will be needed by a fair number of apps, and I'm sure a good number of people potentially interested in Fauxmo will be running Plex on the same device.
