### ISSUE TITLE
Problems with new installation of Fauxmo

### ISSUE THREAD

**Issue by MichaelMuir** [n8henrie/fauxmo#21]
- **Operating system and version**:  Windows Server 2008 SP1
- **Python version**:  3.5.2
- **Fauxmo version**:  0.3.6

## My Issue

2017-02-18 00:42:38 fauxmo:18       INFO     Fauxmo version 0.3.6
2017-02-18 00:42:39 fauxmo:38       DEBUG    3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)]
2017-02-18 00:42:39 fauxmo:15       DEBUG    Attempting to get IP address automatically
2017-02-18 00:42:39 fauxmo:28       DEBUG    Using IP address: 192.168.1.236
2017-02-18 00:42:39 asyncio:979      INFO     <Server sockets=[<socket.socket fd=392, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.236', 12340)>]> is serving
2017-02-18 00:42:39 fauxmo:80       DEBUG    {'action_handler': <fauxmo.handlers.rest.RESTAPIHandler object at 0x03780E70>, 'name': 'fake switch one'}
2017-02-18 00:42:39 asyncio:979      INFO     <Server sockets=[<socket.socket fd=396, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.236', 12341)>]> is serving
2017-02-18 00:42:39 fauxmo:80       DEBUG    {'action_handler': <fauxmo.handlers.rest.RESTAPIHandler object at 0x03B326D0>, 'name': 'fake Indigo switch'}
2017-02-18 00:42:39 asyncio:979      INFO     <Server sockets=[<socket.socket fd=244, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.236', 12342)>]> is serving
2017-02-18 00:42:39 fauxmo:80       DEBUG    {'action_handler': <fauxmo.handlers.rest.RESTAPIHandler object at 0x03780BB0>, 'name': 'fake hass switch by REST API'}
2017-02-18 00:42:39 asyncio:979      INFO     <Server sockets=[<socket.socket fd=400, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.236', 12350)>]> is serving
2017-02-18 00:42:39 fauxmo:104      DEBUG    {'action_handler': <fauxmo.handlers.hass.HassAPIHandler object at 0x03780ED0>, 'name': 'upstairs lamp'}
2017-02-18 00:42:39 fauxmo:106      INFO     Starting UDP server
2017-02-18 00:42:39 asyncio:853      INFO     Datagram endpoint local_addr=('0.0.0.0', 1900) remote_addr=None created: (<_SelectorDatagramTransport fd=404 read=idle write=<idle, bufsize=0>>, <fauxmo.protocols.SSDPServer object at 0x03780FF0>)
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\runpy.py", line 184, in _run_module_as_main    "__main__", mod_spec)
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\Scripts\fauxmo.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\site-packages\fauxmo\cli.py", line 28, in cli    main(config_path=args.config, verbosity=verbosity)
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\site-packages\fauxmo\fauxmo.py", line 114, in main    loop.add_signal_handler(getattr(signal, signame), loop.stop)
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\asyncio\events.py", line 475, in add_signal_handler
    raise NotImplementedError
NotImplementedError

## [WHYT](http://mattgemmell.com/what-have-you-tried)

Disabled the DLNA/UPnP feature of Plex (as per other issue) and confirmed nothing listening on port 1900 using Telnet. 

Forced local IP address of 192.168.1.236 in config.json

---

Please make sure you've taken these steps before submitting a new issue:

- [x ] Include the Python and Fauxmo version in your issue
- [x ] Ensure you're running a supported version of Python
    - Requires Python >= 3.2 for Fauxmo < 0.3.0
    - Requires Python >= 3.4.4 for Fauxmo >= 0.3.0
- [x ] Run Fauxmo in debug mode (`-vvv`) and include relevant output
- [x ] Search the existing (and closed) issues

**Comment by n8henrie** [comment]
Thanks for the bug report, and for including all the required info.

I don't have any Windows machines, but looks like it is [this bug](https://github.com/crossbario/autobahn-python/issues/471) and should likely be amenable to the same simple fix.

However, I don't know if it will introduce any new problems. Would you be willing to [test my new `dev` build](https://github.com/n8henrie/fauxmo#simple-install-of-dev-branch-from-github) and see what happens?

**Comment by MichaelMuir** [comment]
@n8henrie Thanks for your quick reply. First observation for today that I'll get out of the way is that I noticed installing Fauxmo rolled back my Home Assistant install to 0.31.1 from 0.38.3.

I ran the dev install as requested and here is the output:

``C:\Users\Administrator>pip install git+https://github.com/n8henrie/fauxmo.git@dev
Collecting git+https://github.com/n8henrie/fauxmo.git@dev
  Cloning https://github.com/n8henrie/fauxmo.git (to dev) to c:\users\admini~1\appdata\local\temp\2\pip-d4vbgbk_-build
  Requirement already satisfied (use --upgrade to upgrade): fauxmo==0.3.6 from git+https://github.com/n8henrie/fauxmo.git@dev in c:\users\administrator\appdata\
local\programs\python\python35-32\lib\site-packages
Requirement already satisfied: homeassistant==0.31.1 in c:\users\administrator\appdata\local\programs\python\python35-32\lib\site-packages (from fauxmo==0.3.6)
Requirement already satisfied: requests==2.12.4 in c:\users\administrator\appdata\local\programs\python\python35-32\lib\site-packages (from fauxmo==0.3.6)
Requirement already satisfied: pyyaml<4,>=3.11 in c:\users\administrator\appdata\local\programs\python\python35-32\lib\site-packages (from homeassistant==0.31.1
->fauxmo==0.3.6)
Requirement already satisfied: typing<4,>=3 in c:\users\administrator\appdata\local\programs\python\python35-32\lib\site-packages (from homeassistant==0.31.1->fauxmo==0.3.6)
Requirement already satisfied: pytz>=2016.6.1 in c:\users\administrator\appdata\local\programs\python\python35-32\lib\site-packages (from homeassistant==0.31.1->fauxmo==0.3.6)
Requirement already satisfied: pip>=7.0.0 in c:\users\administrator\appdata\local\programs\python\python35-32\lib\site-packages (from homeassistant==0.31.1->fauxmo==0.3.6)
Requirement already satisfied: jinja2>=2.8 in c:\users\administrator\appdata\local\programs\python\python35-32\lib\site-packages (from homeassistant==0.31.1->fauxmo==0.3.6)
Requirement already satisfied: voluptuous==0.9.2 in c:\users\administrator\appdata\local\programs\python\python35-32\lib\site-packages (from homeassistant==0.31.1->fauxmo==0.3.6)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\administrator\appdata\local\programs\python\python35-32\lib\site-packages (from jinja2>=2.8->homeassistant==0.31.1->fauxmo==0.3.6)
Requirement already satisfied: setuptools>=0.6b1 in c:\users\administrator\appdata\local\programs\python\python35-32\lib\site-packages (from voluptuous==0.9.2->homeassistant==0.31.1->fauxmo==0.3.6)
Requirement already satisfied: appdirs>=1.4.0 in c:\users\administrator\appdata\local\programs\python\python35-32\lib\site-packages (from setuptools>=0.6b1->voluptuous==0.9.2->homeassistant==0.31.1->fauxmo==0.3.6)
Requirement already satisfied: six>=1.6.0 in c:\users\administrator\appdata\loca
l\programs\python\python35-32\lib\site-packages (from setuptools>=0.6b1->voluptuous==0.9.2->homeassistant==0.31.1->fauxmo==0.3.6)
Requirement already satisfied: packaging>=16.8 in c:\users\administrator\appdata\local\programs\python\python35-32\lib\site-packages (from setuptools>=0.6b1->voluptuous==0.9.2->homeassistant==0.31.1->fauxmo==0.3.6)
Requirement already satisfied: pyparsing in c:\users\administrator\appdata\local\programs\python\python35-32\lib\site-packages (from packaging>=16.8->setuptools>=0.6b1->voluptuous==0.9.2->homeassistant==0.31.1->fauxmo==0.3.6)
``

and then when running Fauxmo I got the following result:

``2017-02-18 10:19:52 fauxmo:18       INFO     Fauxmo version 0.3.6
2017-02-18 10:19:53 fauxmo:38       DEBUG    3.5.2 (v3.5.2:4def2a2901a5, Jun 25
2016, 22:01:18) [MSC v.1900 32 bit (Intel)]
2017-02-18 10:19:53 fauxmo:28       DEBUG    Using IP address: 192.168.1.236
2017-02-18 10:19:53 asyncio:979      INFO     <Server sockets=[<socket.socket fd
=392, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.236', 12340)>]> is serving
2017-02-18 10:19:53 fauxmo:80       DEBUG    {'action_handler': <fauxmo.handlers.rest.RESTAPIHandler object at 0x0379C130>, 'name': 'fake switch one'}
2017-02-18 10:19:53 asyncio:979      INFO     <Server sockets=[<socket.socket fd=400, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.236', 12341)>]> is serving
2017-02-18 10:19:53 fauxmo:80       DEBUG    {'action_handler': <fauxmo.handlers.rest.RESTAPIHandler object at 0x02D590D0>, 'name': 'fake Indigo switch'}
2017-02-18 10:19:53 asyncio:979      INFO     <Server sockets=[<socket.socket fd=256, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=
('192.168.1.236', 12342)>]> is serving
2017-02-18 10:19:53 fauxmo:80       DEBUG    {'action_handler': <fauxmo.handlers.rest.RESTAPIHandler object at 0x03AFE550>, 'name': 'fake hass switch by REST API'}
2017-02-18 10:19:53 asyncio:979      INFO     <Server sockets=[<socket.socket fd=396, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=
('192.168.1.236', 12350)>]> is serving
2017-02-18 10:19:53 fauxmo:104      DEBUG    {'action_handler': <fauxmo.handlers.hass.HassAPIHandler object at 0x0379C2B0>, 'name': 'upstairs lamp'}
2017-02-18 10:19:53 fauxmo:106      INFO     Starting UDP server
2017-02-18 10:19:53 asyncio:853      INFO     Datagram endpoint local_addr=('0.0.0.0', 1900) remote_addr=None created: (<_SelectorDatagramTransport fd=408 read=idle write=<idle, bufsize=0>>, <fauxmo.protocols.SSDPServer object at 0x0379C0F0>)
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\runpy.py", line 184, in _run_module_as_main    "__main__", mod_spec)
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\Scripts\fauxmo.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\site-packages\fauxmo\cli.py", line 28, in cli    main(config_path=args.config, verbosity=verbosity)
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\site-packages\fauxmo\fauxmo.py", line 114, in main    loop.add_signal_handler(getattr(signal, signame), loop.stop)
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\asyncio\events.py", line 475, in add_signal_handler
    raise NotImplementedError
NotImplementedError``

Unfortunately it doesn't appear to have helped. I'm happy to continue to implement any further changes and perform more testing.

Thanks again.

**Comment by n8henrie** [comment]
Regarding uninstalling the newer HA -- you should be installing into a virtualenv, please see #19.

Odd -- that doesn't seem to have changed anything... Did you uninstall prior to reinstalling?

**Comment by MichaelMuir** [comment]
Doh! I feel a little stupid, I didn't uninstall first as I just assumed installing the dev build would overwrite the previous version. 

So the good news is that Fauxmo is working but I was lead to believe that the Wemo emulation worked with Google Home (upon further research of your documentation I found it doesn't - Echo only).

As I have a Google Home it looks like this was all in vein, let me know if you are keen to explore Google Home compatibility as I'd be happy to help test it if required. Thanks anyway for your help.

**Comment by n8henrie** [comment]
Ha. Well, it helped me fix a bug, so thanks for that. If you feel like donating a Google Home to a good cause I promise to work on Fauxmo compatibility (though I can't promise to actually figure it out). Otherwise, since I don't own one, it would be a pretty difficult feature to add.

I'll go ahead and close this.
