### ISSUE TITLE
Starting UDP on Windows10 Python 3.6

### ISSUE THREAD

**Issue by upstairs-at-erics** [n8henrie/fauxmo#26]
Hi Nathan, great concept, I'm just have some (probably self-inflicted) challenges getting it to spin-up.
Apologies if I'm being dumb. It's very likely :-)
I'm using the sample config with 'auto' ip address setting.

- **Operating system and version**:
Windows 10 
- **Python version**:  
3.6 
- **Fauxmo version** (`fauxmo --help`):
v0.4

## My Issue

an issue starting the UDP server.

fauxmo -c config-sample.json -vvv
D:\>fauxmo -c config-sample.json -vvv
2017-04-30 11:34:49 fauxmo:38       INFO     Fauxmo version 0.4.0
2017-04-30 11:34:49 fauxmo:39       DEBUG    3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
2017-04-30 11:34:49 fauxmo:20       DEBUG    Attempting to get IP address automatically
2017-04-30 11:34:49 fauxmo:33       DEBUG    Using IP address: 192.168.1.93
2017-04-30 11:34:49 fauxmo:103      DEBUG    plugin_vars: {}
2017-04-30 11:34:49 fauxmo:106      DEBUG    device config: {'port': 12340, 'on_cmd': 'http://192.168.1.104/myserver/fakeswitches/01/on', 'off_cmd': 'http://192.168.1.104/myserver/fakeswitches/01/off', 'method': 'GET', 'name': 'fake switch one'}
2017-04-30 11:34:49 asyncio:1067     INFO     <Server sockets=[<socket.socket fd=724, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.93', 12340)>]> is serving
2017-04-30 11:34:49 fauxmo:124      DEBUG    Started fauxmo device: {'name': 'fake switch one', 'plugin': <fauxmo.plugins.simplehttpplugin.SimpleHTTPPlugin object at 0x043121B0>}
2017-04-30 11:34:49 fauxmo:106      DEBUG    device config: {'port': 12341, 'on_cmd': 'http://localhost:54321/devices/garage%20light', 'off_cmd': 'http://localhost:54321/devices/garage%20light', 'on_data': {'isOn': 1}, 'off_data': {'isOn': 0}, 'user': 'this', 'password': 'that', 'method': 'PUT', 'name': 'fake Indigo switch'}
2017-04-30 11:34:49 asyncio:1067     INFO     <Server sockets=[<socket.socket fd=744, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.93', 12341)>]> is serving
2017-04-30 11:34:49 fauxmo:124      DEBUG    Started fauxmo device: {'name': 'fake Indigo switch', 'plugin': <fauxmo.plugins.simplehttpplugin.SimpleHTTPPlugin object at 0x03B13270>}
2017-04-30 11:34:49 fauxmo:106      DEBUG    device config: {'name': 'fake home assistant switch by REST API', 'port': 12342, 'on_cmd': 'http://192.168.1.104:8123/api/services/switch/turn_on', 'off_cmd': 'http://192.168.1.104:8123/api/services/switch/turn_off', 'method': 'POST', 'headers': {'x-ha-access': 'your_hass_password'}, 'on_data': {'entity_id': 'switch.fake_hass_switch'}, 'off_data': {'entity_id': 'switch.fake_hass_switch'}}
2017-04-30 11:34:49 asyncio:1067     INFO     <Server sockets=[<socket.socket fd=436, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.93', 12342)>]> is serving
2017-04-30 11:34:49 fauxmo:124      DEBUG    Started fauxmo device: {'name': 'fake home assistant switch by REST API', 'plugin': <fauxmo.plugins.simplehttpplugin.SimpleHTTPPlugin object at 0x045F3A10>}
2017-04-30 11:34:49 fauxmo:126      INFO     Starting UDP server
UDP
Traceback (most recent call last):
  File "d:\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Scripts\fauxmo.exe\__main__.py", line 9, in <module>
  File "D:\lib\site-packages\fauxmo\cli.py", line 28, in cli
    main(config_path_str=args.config, verbosity=verbosity)
  File "D:\lib\site-packages\fauxmo\fauxmo.py", line 131, in main
    sock=make_udp_sock())
  File "D:\lib\site-packages\fauxmo\utils.py", line 76, in make_udp_sock
    sock.bind(('', 1900))
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

---

Please make sure you've taken these steps before submitting a new issue:

- [x] Try to reproduce the issue with Fauxmo installed in a
  [venv](https://docs.python.org/3/library/venv.html)
I'm using a clean python 3.6.0

- [x] Ensure you're running a supported version of Python
    - Requires Python >= 3.2 for Fauxmo < 0.3.0
    - Requires Python >= 3.4.4 for Fauxmo >= 0.3.0
    - Requires Python >= 3.6.0 for Fauxmo >= 0.4.0
- [x] Run Fauxmo in debug mode (`-vvv`) and include relevant output

as above

- [x] Include your Fauxmo `config.json`
unchanged. as per github

- [x] Search the existing (including closed) issues
I dont see anyone else getting this

**Comment by n8henrie** [comment]
Wow, thanks for following the template and providing a thorough / complete bug report!

I don't have a Windows machine regularly available, so I may be a bit limited in my ability to debug this.

To start:

- Do you have any other services running on 1900?
- Is there error intermittent (e.g. if you wait an hour) or every time you try to start Fauxmo?

**Comment by WeldFire** [comment]
After trying to set up Fauxmo on a Linux machine, I also ran into this issue. For me the port 1900 was being consumed by another process. Killing this process allows Fauxmo to start fully. You can try viewing ports being held in Windows 10 by going to the Resource Monitor from Task Manager and then looking at "Listening Ports". On my Windows 10 machine it appears that by default Windows 10 process svchost.exe holds this port hostage. Unfortunately for me and as it appears on my machine, also you, need that process running leaving us unable to run this application unless we can figure out how to share this port or leverage a different one.

**Comment by n8henrie** [comment]
Huh, thanks for chiming in on this issue. I had something similar where my `test_udp_search` function was failing on macOS for a few days -- for the life of me I couldn't find anything listening on that port, so I finally just rebooted and it started working again.

I've split off a new little bug fix branch to work on this issue -- for starters, I reordered the lines in `make_udp_sock()` in `fauxmo.utils` so that 1900 isn't bound until the reuseaddr (and reuseport if available) options are set.

@upstairs-at-erics and @WeldFire -- can you guys give a shot to installing the [`fix-busy-sockets`](https://github.com/n8henrie/fauxmo/tree/fix-busy-sockets) branch and see if that helps this issue?

**Comment by WeldFire** [comment]
The fix-busy-sockets branch seems to fix the issue for me, thanks for your help on this issue and your work on this project!

**Comment by n8henrie** [comment]
@upstairs-at-erics -- since you opened the issue, can you give a shot to the new `dev` branch (which has merged `fix-busy-sockets`) and see if it works for you? If I don't hear back in a few days I'll go ahead and merge into master and close.

**Comment by n8henrie** [comment]
Merged into master, closing due to no response.
