### ISSUE TITLE
Many typos from pip3 install

### ISSUE THREAD

**Issue by ShuffleBit** [n8henrie/fauxmo#27]
- **Ubuntu 16.04**:
- **Python 3.5.2**:
- **Fauxmo version unknown - __version__ is all that prints** (`fauxmo --help`):

2017-08-03 10:50:24 fauxmo:37       INFO     Fauxmo version {__version__}

## [WHYT](http://mattgemmell.com/what-have-you-tried)
I edited the installed files, gave up on:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/fauxmo/fauxmo.py", line 86, in main
    module = importlib.import_module(modname)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named '{__package__}'

I assumed the project is abandoned.

---

Please make sure you've taken these steps before submitting a new issue:

- [ ] Try to reproduce the issue with Fauxmo installed in a
  [venv](https://docs.python.org/3/library/venv.html)
- [ ] Ensure you're running a supported version of Python
    - Requires Python >= 3.2 for Fauxmo < 0.3.0
    - Requires Python >= 3.4.4 for Fauxmo >= 0.3.0
    - Requires Python >= 3.6.0 for Fauxmo >= 0.4.0
- [ ] Run Fauxmo in debug mode (`-vvv`) and include relevant output
- [ ] Include your Fauxmo `config.json`
- [ ] Search the existing (including closed) issues

**Comment by n8henrie** [comment]
> I assumed the project is abandoned.

Huh? My last push was 2 months ago.

Please read [the README](https://github.com/n8henrie/fauxmo/tree/ecbb063fd920bdb5c678aa3ac95dadaa4805c28c#introduction) and the full issue template before opening an issue -- the latest version of Fauxmo requires Python 3.6, which supports f-strings. I think this is pretty well documented, and you've stated above that you're only running 3.5.2.

From the README:

> As of version v0.4.0, Fauxmo uses several API features and f-strings that require Python 3.6+.

From the bottom of the issue template (included in your issue above):

> Ensure you're running a supported version of Python
Requires Python >= 3.2 for Fauxmo < 0.3.0
Requires Python >= 3.4.4 for Fauxmo >= 0.3.0
Requires Python >= 3.6.0 for Fauxmo >= 0.4.0
