### ISSUE TITLE
Syntax error on  fauxmo -c /home/pi/config.json -vvv

### ISSUE THREAD

**Issue by Max0412** [n8henrie/fauxmo#30]
- **Operating system and version**: raspberry pi  Linux version 4.9.41-v7+
- **Python version**: 3.6
- **Fauxmo version** (`fauxmo --version`): 0.4.4.

## My Issue

(venv) pi@raspberrypi:~/venv $ fauxmo -c /home/pi/config.json -vvv
Traceback (most recent call last):
  File "/home/pi/venv/bin/fauxmo", line 7, in <module>
    from fauxmo.cli import cli
  File "/home/pi/venv/lib/python3.5/site-packages/fauxmo/cli.py", line 10, in <module>
    from fauxmo.fauxmo import main
  File "/home/pi/venv/lib/python3.5/site-packages/fauxmo/fauxmo.py", line 37
    logger.info(f"Fauxmo version {__version__}")
                                              ^
SyntaxError: invalid syntax

I´ve worked thru the commands and with the last command i get this error.

config ist just cp the original config sample

## [WHYT](http://mattgemmell.com/what-have-you-tried)

i´ve tried to google it but haven´t found a solution

**Comment by n8henrie** [comment]
You say you’re using 3.6 but looks like 3.5 based on your traceback, which would explain the error. Can you double check?

**Comment by Max0412** [comment]
Hey,
thanks for the answer, i´ve checked that and my result is, that somehow i have
Python 3.6 outside of the venv but inside i´ve 3.5.3.

**Comment by n8henrie** [comment]
I recommend you try deleting the venv and use the full path to python3.6 when you create the venv, something like

```shell_session
$ rm -r venv/
$ /path/to/python3.6 --version
3.6.2
$ /path/to/python3.6 -m venv venv
$ venv/bin/python --version
3.6.2
$ source venv/bin/activate
$ pip install --upgrade fauxmo
```

More or less.

**Comment by Max0412** [comment]
venv/bin/python --version
Python 3.6.0
that worked pretty good but now i have another problem, 

`(venv) pi@raspberrypi:~ $ fauxmo -c config.json -vvv
2017-10-02 18:40:57 fauxmo:37       INFO     Fauxmo v0.4.4
2017-10-02 18:40:57 fauxmo:38       DEBUG    3.6.0 (default, Sep 29 2017, 20:26:31)
[GCC 6.3.0 20170516]
Traceback (most recent call last):
  File "/home/pi/venv/bin/fauxmo", line 11, in <module>
    sys.exit(cli())
  File "/home/pi/venv/lib/python3.6/site-packages/fauxmo/cli.py", line 30, in cli
    main(config_path_str=args.config, verbosity=verbosity)
  File "/home/pi/venv/lib/python3.6/site-packages/fauxmo/fauxmo.py", line 50, in main
    config = json.loads(config_path.read_text())
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 15 column 13 (char 459)
`

**Comment by n8henrie** [comment]
If the current problem is solved, please close this issue and start a new one.

It looks like your JSON is invalid, please see [the FAQ](https://github.com/n8henrie/fauxmo#troubleshooting--faq) on how to validate.

**Comment by Max0412** [comment]
Ok thank your!
