### ISSUE TITLE
CommandLinePlugin

### ISSUE THREAD

**Issue by babybantick** [n8henrie/fauxmo#46]
OS: Raspian
Python: 3.6.3
set .json as:
{
  "FAUXMO": {
    "ip_address": "auto"
  },
  "PLUGINS": {
    "CommandLinePlugin": {
      "path": "/path/to/commandlineplugin.py",
      "DEVICES": [
        {
            "name": "output stuff to a file",
            "port": 49915,
            "on_cmd": "touch testfile.txt",
            "off_cmd": "rm testfile.txt"
            "state_cmd": "ls testfile.txt"
        }
      ]
    }
  }
}
Error:
2018-01-21 00:20:01 fauxmo:37       INFO     Fauxmo v0.4.5
2018-01-21 00:20:01 fauxmo:38       DEBUG    3.6.3 (default, Jan 20 2018, 23:01:25)
[GCC 6.3.0 20170516]
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.6.3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/pyenv/versions/3.6.3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/pyenv/versions/3.6.3/lib/python3.6/site-packages/fauxmo/cli.py", line 34, in <module>
    cli()
  File "/opt/pyenv/versions/3.6.3/lib/python3.6/site-packages/fauxmo/cli.py", line 30, in cli
    main(config_path_str=args.config, verbosity=verbosity)
  File "/opt/pyenv/versions/3.6.3/lib/python3.6/site-packages/fauxmo/fauxmo.py", line 50, in main
    config = json.loads(config_path.read_text())
  File "/opt/pyenv/versions/3.6.3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/pyenv/versions/3.6.3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/pyenv/versions/3.6.3/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 14 column 13 (char 334)

**Comment by n8henrie** [comment]
Missing a comma at the end of: `"off_cmd": "rm testfile.txt"`

Please use `python3 -m json.tool` (or jsonlint, or some other tool) to validate your json.
