### ISSUE TITLE
 No such file or directory: '/path/to/commandlineplugin.py'

### ISSUE THREAD

**Issue by babybantick** [n8henrie/fauxmo#47]
OS: Raspian 
Python: 3.6.3
Json:
{
"FAUXMO": {
"ip_address": "auto"
},
"PLUGINS": {
"CommandLinePlugin": {
"path": "/path/to/commandlineplugin.py",
"DEVICES": [
{
"name": "output stuff to a file",
"port": 49915,
"on_cmd": "touch testfile.txt",
"off_cmd": "rm testfile.txt",
"state_cmd": "ls testfile.txt"
}
]
}
}
}

Output:
pi@raspberrypi:~/Desktop $ bash "Start Alexa Devices.sh"2018-01-21 23:20:05 fauxmo:37       INFO     Fauxmo v0.4.5
2018-01-21 23:20:05 fauxmo:38       DEBUG    3.6.3 (default, Jan 20 2018, 23:01:25) 
[GCC 6.3.0 20170516]
2018-01-21 23:20:05 fauxmo:24       DEBUG    Attempting to get IP address automatically
2018-01-21 23:20:05 fauxmo:37       DEBUG    Using IP address: 192.168.1.137
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.6.3/lib/python3.6/site-packages/fauxmo/fauxmo.py", line 86, in main
    module = importlib.import_module(modname)
  File "/opt/pyenv/versions/3.6.3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fauxmo.plugins.commandlineplugin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pyenv/versions/3.6.3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/pyenv/versions/3.6.3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/pyenv/versions/3.6.3/lib/python3.6/site-packages/fauxmo/cli.py", line 34, in <module>
    cli()
  File "/opt/pyenv/versions/3.6.3/lib/python3.6/site-packages/fauxmo/cli.py", line 30, in cli
    main(config_path_str=args.config, verbosity=verbosity)
  File "/opt/pyenv/versions/3.6.3/lib/python3.6/site-packages/fauxmo/fauxmo.py", line 90, in main
    module = module_from_file(modname, path_str)
  File "/opt/pyenv/versions/3.6.3/lib/python3.6/site-packages/fauxmo/utils.py", line 71, in module_from_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/commandlineplugin.py'

---------------------------

I'm starting faux with:
cd /home/pi/HomeAutomation
"$(pyenv root)"/versions/3.6.3/bin/python3.6 -m fauxmo.cli -c config.json -vvv

I receive syntax errors whenever i try to call fauxmo using just "python3"

**Comment by n8henrie** [comment]
In your config, I hope you are replacing `/path/to/commandlineplugin.py`
with the actual path to the file, right?

**Comment by n8henrie** [comment]
No response in over 10 days, will be closing soon.
